### ISSUE TITLE
Doesn't work on Windows 10 version 1709

### ISSUE THREAD

**Issue by Agent21** [justaminer/hsrm-fork#1]
Downloaded this miner and ran it on my first rig with Windwos version 1703 and worked fine, ran it on my second miner rig with Windows 10 version 1709 on it and it gave an error and closed. I updated my first miner to Windows 10 version 1709 and now it won't work on the first rig either. Not sure what it is about this windows version yet but I'm looking further into this.

**Comment by justaminer** [comment]
Bug is fixed, use new version.
